### ISSUE TITLE
Website for Droid-ify

### ISSUE THREAD

**Issue by tashijayla** [Droid-ify/client#110]
Maybe it would also be good to explain why Droid-ify is better then F-droid on the future website 😉

**Comment by uli-on** [comment]
<small font-color="#888">((very silently speaking aside: please, can you stop falsifying votes by upvoting your own or triple voting other posts like in 108? thanks.))</small>

**Comment by tashijayla** [comment]
> <small font-color="#888">((very silently speaking aside: please, can you stop falsifying votes by upvoting your own or triple voting other posts like in 108? thanks.))</small>

OK, thanks for the feedback 🤐

**Comment by Iamlooker** [comment]
I can't develop websites, It would be highly appreciated if somebody else can help me with this.

**Comment by gallegonovato** [comment]
Good afternoon @Iamlooker

On what domain or where were you thinking of hosting the website?.

What are you looking for or what structure would you be thinking about?.

Best regards

**Comment by Iamlooker** [comment]
I will probably host it on GitHub pages

**Comment by gallegonovato** [comment]
good afternoon @Iamlooker don't pay attention to the Pull requests I made since I'm doing tests for the web. A hug

**Comment by vertigo220** [comment]
@gallegonovato I assume you're working on something, do you have enough done for people to check out and provide feedback? As for explaining what makes Droid-ify better, perhaps an issue or discussion should be created to gather user input to see why those using it choose to do so over F-Droid and other alternatives.

**Comment by gallegonovato** [comment]
good afternoon @vertigo220

the truth is that it was impossible for me to make any progress. I was just checking the emeil when I got the notice. 

I've been on a streak you wouldn't believe. But it's the truth: I was in the hospital, a cousin died, my grandmother died, my father had surgery, and a few days ago my father died. And I could go on, but even though they say men don't cry.......

For which I beg your pardon. I know you are not to blame but you deserve an explanation for my lack of progress.

I am currently broken physically, mentally and in every way. 

So if someone wants to take over from me I would appreciate it. Since right now my thoughts are a pure mess and crap.

I beg your pardon, but fuc.... life is giving me all over the place.

A hug

**Comment by vertigo220** [comment]
No worries, and sorry to hear everything's going so badly. Nobody's going to hold it against you for not wanting to work on this, you need to take time to heal and deal with life.

**Comment by Iamlooker** [comment]
@gallegonovato I am so sorry for all your loss, I know exactly how it feels like to lose a loved one. Take care and take your time.

**Comment by tashijayla** [comment]
@gallegonovato sorry to hear how life has been for you lately, just wanting to say thank you for all the great stuff you have done for this project I really appreciate it, things will always get better 💚🌹❤️‍🔥

**Comment by gallegonovato** [comment]
Good afternoon @vertigo220 @Iamlooker @tashijayla

Thank you very much for your support and understanding. And for all your words.

The truth is that life sucks. I do nothing but eat my head and I think I'm going into a depression, because I don't even want to get out of bed. And these dates that are already there ....

But please, I only ask you to enjoy the holidays and these special dates. And that you enjoy a lot of your families. And may you spend a VERY MERRY CHRISTMAS WITH YOUR LOVED ONES.

Remember that in Galicia you have a friend who carries you in his heart and head 👍 

A big hug ❤️

**Comment by tashijayla** [comment]
I'm sending you good vibes, wishing you a feeling of peace and direction for the future ahead of you, your a very special person and I just want you to know that I'm thinking of you this Christmas 
💚💛🧡🌟🧡💛💚

**Comment by tashijayla** [comment]
@gallegonovato 
I'm sending you good vibes, wishing you a feeling of peace and direction for the future ahead of you, your a very special person and I just want you to know that I'm thinking of you this Christmas
💚💛🧡🌟🧡💛💚

**Comment by Iamlooker** [comment]
@iamthecloverly can you help with building a site for Droid-ify?

**Comment by iamthecloverly** [comment]
Dear @Iamlooker ,

Thank you for considering me for the development of your open source project's website. I'm excited to be a part of this project and contribute to the open source community.

We have reviewed the requirements and are confident that we can deliver a high-quality website that meets your needs and exceeds your expectations.

Thank you again for the opportunity to work with you. We look forward to collaborating and bringing your vision to life.

Sincerely, SriBalaji

**Comment by gallegonovato** [comment]
Good afternoon:

First of all thank you all very much for your patience with me and for your understanding.

I wanted to wish you a Happy New Year.

I'm still on a bad streak, but I'm getting help not to fall into bad things. Since it's a real drag to live.

Thanks to @iamthecloverly for all your help and for helping this great project.

And millions of thanks to @Iamlooker , @tashijayla and millions of other users for being WONDERFUL PEOPLE AND WITH A GREAT HEART.

A hug from your friend

**Comment by Iamlooker** [comment]
You can communicate with @iamthecloverly, he working on a website. He is currently on a break but I assume you both can atill commute.

**Comment by Iamlooker** [comment]
> Is there's a place to start? I would like to contribute.

You can communicate with @iamthecloverly, he working on a website. He is currently on a break but I assume you both can atill commute.

**Comment by Iamlooker** [comment]
😉

**Comment by Iamlooker** [comment]
# A new home for [Droid-ify](https://github.com/Droid-ify/client)

![Poster (6)](https://github.com/Droid-ify/client/assets/60404093/da1ab529-a520-4edf-88a0-b494866903da)
