### ISSUE TITLE
[BUG] Updating apps hangs device and forces reboot.

### ISSUE THREAD

**Issue by rokejulianlockhart** [Droid-ify/client#352]
**Describe the bug**

> Per the title, updating all apps that require updates hangs device and forces reboot.

**To Reproduce**

Steps to reproduce the behaviour:

0. Refresh all repositories.
0. Initiate update of all apps.

**Expected behaviour**

> Updating apps shouldn't reboot the device.

**Smartphone (please complete the following information):**

 - Device: Fairphone FP4
 - OS: Android
 - Version: 13 (FP4.SP29.B.069.20230510)

**Additional context**

https://gitlab.com/fdroid/fdroidclient/-/issues/2626

**Comment by rokejulianlockhart** [comment]
@Iamlooker,

I used https://play.google.com/store/apps/details?id=ccc71.lr&hl=en_SG to view the logcat logs (it doesn't need root really) and until the phone shutdown, the log stated repeatedly (in blue) that something about the accessibility limit was reached. It also seems that only the system GUI input thread was affected - although I could see my finger presses registered immediately, and the logcat updated as if the phone wasn't reacting slowly, but any UI interactions very quickly went from slow to literally unregistered until the phone rebooted.

Installing apps doesn't appear to be noticeably slow.

**Comment by ChristenEdmundson** [comment]
I find this happens for me sometimes also on my pixel 3, but doesn't cause a reboot, it just makes my phone unresponsive for a bit while it processes all the updates. Hasn't seemed to happen the last couple times though

**Comment by Iamlooker** [comment]
Very weird and concerning, I will try to make "Update all" more lightweight. Maybe that will help.

**Comment by Cris-Edmundson** [comment]
@Iamlooker honestly I kinda thought there might have already been an update to fix the issue and I just missed it, since like I said- its been pretty smooth the last couple times I've used update all. But looking at the version numbers I don't think there was, so I'm not sure why it stopped really being an issue for me

Probably wouldn't hurt to take a look at possible performance improvements though

(Also thanks for a rad f-droid client, I really enjoy using it 😊)
