### ISSUE TITLE
[BUG] Installer type randomly switches to session installer

### ISSUE THREAD

**Issue by SirenGlitch** [Droid-ify/client#461]
**Describe the bug**
Installation type randomly switches from Shizuku to session installer for seemingly no reason

**To Reproduce**
1. Go to Settings --> Installation Types
2. Change installation type to Shizuku installer
3. Go about using Droid-ify normally for updates, installs, etc.
4. Once the built-in Package Installer dialog shows up then it has worked

**Expected behavior**
Selected Installation Type stays as the selected option unless changed by the user

**Screenshots**
N/A

**Smartphone (please complete the following information):**
 - Device: OnePlus 6T
 - OS: Android 11
 - Version: V0.5.8.3

**Additional context**

**Comment by Iamlooker** [comment]
It might be because you lost permission to shixuku or maybe shixuku binder died

**Comment by SirenGlitch** [comment]
> It might be because you lost permission to shixuku or maybe shixuku binder died

I've re-enabled the Droid-ify Shizuku permission as in the latest update there was a change to the permission handling. This was probably the issue but will confirm

**Comment by lu-ckystars** [comment]
i am also having this issue on 0.5.8.3 pixel 4a, calyx and it did it on graphene as well. ive checked and shizuku never stopped running and sometimes i will go into settings and set install method to shizuku, restart droid-ify and install method is back to session. it works correctly id estimate about 85% of the time. i think it may be a shizuku issue because i have had the same issue with ff-updater.

**Comment by Iamlooker** [comment]
This is fixed in the alpha build and will be available in next release

**Comment by Iamlooker** [comment]
You can download the latest alpha builds from our [Telegram Community](https://t.me/droidifyc) or [Actions Tab](https://github.com/Droid-ify/client/actions/workflows/build_debug.yml)
