### ISSUE TITLE
Rename default repo for better readeblity

### ISSUE THREAD

**Issue by Rexadev** [Droid-ify/client#641]
Rename to these

1. Add brackets to indicate channel - KDE Android (Nightly),  KDE Android (Release), FluffyChat **(**Nightly**)**
3. Remove "F-droid repo" - Collabra Office ~F-Droid Repo~, micro-G, IzzyOnDroid , ...
4. Remove "Official Releases" -Guardian Project ~Official Releases~
5. Remove "Repo (FOSS)" - Molly F-Droid ~Repo (FOSS)~
6. Remove "Repo" - Brair Project ~Repo~
7. Remove "Project" - Brair ~Project~ Repo
8. Remove "F-droid" - Session ~F-droid~
9. Remove "The" - ~The~ Calyx Institute ~Fdroid repo~

**Comment by Elbullazul** [comment]
As far as I know it's the repo owners that set the name, Droid-ify only displays it.

Probably not a good idea to change repo names if that's the case.

**Comment by spider1163** [comment]
Yes we shouldn't rename the name given by the owner

**Comment by CloneWith** [comment]
Agree with the idea to keep the given repository name, since the owner named repositories intentionally.

However we can give a alternative name to it.

Take `Guardian Project Official Releases` for an example. You can set the alternative name to 'Guardian Project'. Then it can be displayed in repository view like this:

- Guardian Project *Guardian Project Official Releases* (alternative first then original, can be set to show alternative names only when necessary)
- KDE Android *nightly* (alternative last, better for custom comments and labels)
